[package]
name = "dccmd-rs"
version = "0.1.2"
edition = "2021"
description = "A command line client for DRACOON"
author = "Octavio Simone"
license = "MIT"
readme = "README.md"

[[bin]]
name = "dccmd-rs"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# DRACOON API
dco3 = "0.6.1"

# CLI helpers
clap = { version = "4.4.7", features = ["derive"] }
indicatif = "0.17.7"
console = "0.15.7"
dialoguer = "0.11.0"

# async runtime and utils
tokio = { version = "1.32.0", features = ["full"] }
futures-util = "0.3.29"
async-recursion = "1.0.5"

# logging and tracing
tracing = "0.1.40"
tracing-subscriber = {version = "0.3.17", features = ["env-filter"]}

# utils
chrono = "0.4.31"
thiserror = "1.0.50"
dotenv = "0.15.0"

# credentials
keyring = "2.0.5"
config = "0.13.4"
serde = { version = "1.0.193", features = ["derive"] }
lazy_static = "1.4.0"

