[package]
name = "dccmd-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.8", features = ["derive"] }
reqwest = {version = "0.11.14", features = ["json"]}
chrono = "0.4.1"
keytar = "0.1.6"
thiserror = "1.0.2"
base64 = "0.13.0"
dotenv = "0.15.0"
serde = { version = "1.0.159", features = ["derive"] }
tokio = { version = "1.27.0", features = ["full"] }
async-trait = "0.1.68"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
colored = "2.0.0"
