[package]
name = "dccmd-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# DRACOON API
dco3 = "0.4.1"

# CLI helpers
clap = { version = "4.1.8", features = ["derive"] }
indicatif = "0.17.3"
console = "0.15.5"
dialoguer = "0.10.4"

# async runtime and utils
tokio = { version = "1.27.0", features = ["full"] }
futures-util = "0.3.28"
async-recursion = "1.0.4"

# logging and tracing
tracing = "0.1.37"
tracing-subscriber = {version = "0.3.17", features = ["env-filter"]}

# utils
chrono = "0.4.1"
thiserror = "1.0.2"
dotenv = "0.15.0"

# credentials
keyring = "2.0.2"

