[package]
name = "dccmd-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.8", features = ["derive"] }
reqwest = "0.11.14"
chrono = "0.4.1"
keytar = "0.1.6"
thiserror = "1.0.2"